# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
# MindIE is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

import time
from enum import Enum

from pydantic import BaseModel, Field, PrivateAttr

import anyio

from motor.common.resources.instance import PDRole
from motor.coordinator.tracer.tracing import TraceObj
from motor.coordinator.domain.agent_hint import AgentHintInfo


class RequestType(Enum):
    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    TRITON = "triton"
    TGI = "tgi"
    VLLM = "vllm"
    MINDIE = "mindie"


class ReqState(Enum):
    ARRIVE = 'Arrive'               # Request arrive
    E_SCHEDULING = 'E_Scheduling'   # Currently scheduling E instance
    E_ALLOCATED = 'E_Allocated'     # Allocated E instance
    P_SCHEDULING = 'P_Scheduling'   # Currently scheduling P instance
    P_ALLOCATED = 'P_Allocated'     # Allocated P instance
    PREFILL_END = 'Prefill End'     # Prefill completed
    FIRST_TOKEN_FINISH = 'First Token Finish'   # First decoded token
    D_SCHEDULING = 'D_Scheduling'   # Currently scheduling D instance
    D_ALLOCATED = 'D_Allocated'     # Allocated D instance
    DECODE_END = 'Decode End'       # Decode completed
    INVALID = 'Invalid'             # Invalid state
    TIMEOUT = 'Timeout'             # Request timeout
    EXCEPTION = 'Exception'         # Request exception
    RECOMPUTE = 'Recompute'         # Recomputation


class RequestInfo(BaseModel):
    req_id: str = Field(..., description="Request ID generated by RequestManager")
    req_data: dict = Field(..., description="Request json content")
    req_len: int = Field(..., description="Request body length")
    token_ids: list[int] | None = Field(
        default=None,
        description="Prompt token ids tokenized once at routing (KV affinity); reused for "
                    "prefill load accounting so load and affinity share the same token unit",
    )
    api: str = Field(..., description="API need to be forwarded")
    entry_api: str = Field(
        default="",
        description="Original client HTTP path (e.g. v1/chat/completions); unchanged on recompute retry",
    )
    recompute_engine_mode: str | None = Field(
        default=None,
        description="Set to 'completions' when recompute retry uses v1/completions body",
    )
    client_expects_chat_shape: bool = Field(
        default=False,
        description="True if the original client request was chat completions (messages present at ingress)",
    )
    state: ReqState = Field(default=ReqState.ARRIVE, description="Request current status")
    status: dict[ReqState, float] = Field(default={}, description="Request status time")
    trace_obj: TraceObj = Field(default_factory=TraceObj, description="Tracing object")
    _p_cancel_scope: anyio.CancelScope | None = PrivateAttr(default=None)
    _d_cancel_scope: anyio.CancelScope | None = PrivateAttr(default=None)
    _e_cancel_scope: anyio.CancelScope | None = PrivateAttr(default=None)
    prompt_tokens_details: dict = Field(default={}, description="prefill prompt_tokens_details")
    agent_hint_info: AgentHintInfo = Field(
        default_factory=AgentHintInfo,
        description="从请求 agent_hint 解析的结构化信息，供 Scheduler 使用",
    )

    def __init__(self, **data):
        super().__init__(**data)
        self.status[ReqState.ARRIVE] = time.time()
        
    @property
    def is_cancelled(self) -> bool:
        return (self._p_cancel_scope and self._p_cancel_scope.cancel_called) \
            or (self._d_cancel_scope and self._d_cancel_scope.cancel_called) \
            or (self._e_cancel_scope and self._e_cancel_scope.cancel_called)

    def effective_entry_api(self) -> str:
        """Path used for client-contract checks (Chat vs Completion); falls back to ``api``."""
        return self.entry_api or self.api

    def update_state(self, new_state: ReqState):
        self.state = new_state
        self.status[new_state] = time.time()

    def update_prompt_tokens_details(self, prompt_tokens_details: dict):
        self.prompt_tokens_details = prompt_tokens_details

    def set_cancel_scope(self, cancel_scope: anyio.CancelScope, role: PDRole):
        if role == PDRole.ROLE_P:
            self._p_cancel_scope = cancel_scope
        elif role == PDRole.ROLE_D:
            self._d_cancel_scope = cancel_scope
        elif role == PDRole.ROLE_E:
            self._e_cancel_scope = cancel_scope
    
    def cancel_scope(self):
        if self._p_cancel_scope and not self._p_cancel_scope.cancel_called:
            self._p_cancel_scope.cancel()
        if self._d_cancel_scope and not self._d_cancel_scope.cancel_called:
            self._d_cancel_scope.cancel()
        if self._e_cancel_scope and not self._e_cancel_scope.cancel_called:
            self._e_cancel_scope.cancel()
